### ISSUE TITLE
[BUG] Pixels dont place

### ISSUE THREAD

**Issue by OGMatrix** [WorldObservationLog/reddit-place-script-2023#12]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

Program says pixel are placed but when I look at r/place nothing has been place at the coords

## Expected behavior

Pixels are being placed

**Comment by hedihadi** [comment]
this problem started occuring after the page expand

**Comment by Antoine489** [comment]
Same for me sometimes it work but the majority of time it doesnt work

**Comment by OGMatrix** [comment]
> Same for me sometimes it work but the majority of time it doesnt work

tried like 6 times and hasn't worked once

**Comment by Antoine489** [comment]
Yes sorry I made a mistake in my message I'm not English I meant some place of pixel work but it's very rare

**Comment by OGMatrix** [comment]
yes like one time one pixel placed but the others werent placed

**Comment by Chepycou** [comment]
All workers are trying to place the same pixel

**Comment by ghost** [comment]
I have thousands of bots but it seems for all the successful pixels i see in the console only 5-10% of them actually appear on the map

**Comment by ghost** [comment]
I have found the bug!

Issue happens not just in the program, but also in my browser
When i place a pixel, it says it is placed but on refresh it is not.
However if I use a vpn to go to america then it works.

So either:
1. Some sort of backend region server is broken
2. I am IP shadow banned

But since im using 1250 proxies this means they must be getting ip banned with just 2 repeats and im not sure how
I haven't used my main account in any programs, only the browser.
However I have used multiple reddit accounts on my IP. It is possible that reddit have ip shadowbanned me for using too many accounts at once?

**Comment by WorldObservationLog** [comment]
The coords conventing bug due to the canvas updating has been fixed in commit 663b21e
I suggest to use US ip to reduce the risk of banning or shadow banning. According to my experience in r/place 2022, US ip can significantly reduces the possibility of account being banned.
